# Generated by Django 5.2 on 2025-04-19 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_inscriptions', '0002_remove_student_date_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la formation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duree_heures', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée totale en heures')),
                ('objectifs', models.TextField(blank=True, null=True, verbose_name='Objectifs')),
                ('prerequis', models.TextField(blank=True, null=True, verbose_name='Prérequis')),
                ('est_active', models.BooleanField(default=True, verbose_name='Est active')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_session', models.CharField(max_length=255, verbose_name='Nom de la session')),
                ('date_debut_session', models.DateField(verbose_name='Date de début de la session')),
                ('date_fin_session', models.DateField(verbose_name='Date de fin de la session')),
                ('capacite_max', models.PositiveIntegerField(verbose_name='Capacité maximale')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de la session')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la session')),
                ('capacite_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité minimale')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gestion_formations.formation', verbose_name='Formation')),
                ('instructor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_principales', to='gestion_inscriptions.instructor', verbose_name='Formateur principal')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['date_debut_session'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la séance')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de la séance')),
                ('sujet_aborde', models.CharField(blank=True, max_length=255, null=True)),
                ('est_annulee', models.BooleanField(default=False)),
                ('note_seance', models.TextField(blank=True, null=True, verbose_name='Notes de la séance')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_enseignees', to='gestion_inscriptions.instructor', verbose_name='Formateur de la séance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='gestion_formations.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
