# Generated by Django 5.2 on 2025-04-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_formations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='lieu',
            new_name='lieu_seance',
        ),
    ]
