# Generated by Django 5.2 on 2025-10-24 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='seance',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='Formateur de la séance'),
        ),
        migrations.AddField(
            model_name='seance',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='gestion_formations.room', verbose_name='Salle'),
        ),
        migrations.AddField(
            model_name='session',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gestion_formations.formation', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='session',
            name='instructor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_principales', to=settings.AUTH_USER_MODEL, verbose_name='Formateur principal'),
        ),
        migrations.AddField(
            model_name='seance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='gestion_formations.session', verbose_name='Session'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('session', 'date', 'heure_debut'), name='unique_seance_time_per_session'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='heure_fin_apres_debut'),
        ),
    ]
