# Generated by Django 5.2 on 2025-04-28 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_formations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='Formateur de la séance'),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_principales', to=settings.AUTH_USER_MODEL, verbose_name='Formateur principal'),
        ),
    ]
