# Generated by Django 5.2 on 2025-10-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_formations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='date_debut_formation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début de la formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='date_fin_formation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de la formation'),
        ),
    ]
