# Generated by Django 5.2 on 2025-04-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_formations', '0002_rename_lieu_seance_lieu_seance'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='statut',
            field=models.CharField(choices=[('PLANNED', 'Planifiée'), ('OPEN', 'Ouverte aux inscriptions'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=50, verbose_name='Statut de la session'),
        ),
    ]
