# Generated by Django 5.2 on 2025-04-29 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_formations', '0004_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='lieu_seance',
        ),
        migrations.AddField(
            model_name='seance',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='gestion_formations.room', verbose_name='Salle'),
        ),
    ]
