# Generated by Django 5.2 on 2025-04-25 12:03

import gestion_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_users', '0002_customuser_adress_customuser_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=gestion_users.models.user_directory_path, verbose_name='Photo de profil'),
        ),
    ]
