# Generated by Django 5.2 on 2025-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('UNEXCUSED', 'Non excusé'), ('EXCUSED', 'Excusé'), ('LATE', 'En retard')], default='ABSENT', max_length=50, verbose_name='Statut de présence')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=50, verbose_name="Statut de l'inscription")),
                ('date_statut', models.DateField(blank=True, null=True, verbose_name='Date de changement de statut')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
    ]
