# Generated by Django 5.2 on 2025-04-19 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_users', '0002_customuser_adress_customuser_date_naissance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instructor', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('specialite_enseignement', models.CharField(blank=True, max_length=255, null=True, verbose_name="Spécialité d'enseignement")),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('numero_etudiant', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro Étudiant')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
    ]
