# Generated by Django 5.2 on 2025-04-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_naissance',
        ),
    ]
