# Generated by Django 5.2 on 2025-10-24 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_formations', '0002_initial'),
        ('gestion_inscriptions', '0001_initial'),
        ('gestion_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instructor', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('specialite_enseignement', models.CharField(blank=True, max_length=255, null=True, verbose_name="Spécialité d'enseignement")),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('numero_etudiant', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro Étudiant')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gestion_formations.seance', verbose_name='Séance'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gestion_formations.session', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gestion_inscriptions.enrollment', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gestion_inscriptions.student', verbose_name='Étudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'seance')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'session')},
        ),
    ]
