# Generated by Django 5.2 on 2025-04-19 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_formations', '0002_rename_lieu_seance_lieu_seance'),
        ('gestion_inscriptions', '0002_remove_student_date_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=50, verbose_name="Statut de l'inscription")),
                ('date_statut', models.DateField(blank=True, null=True, verbose_name='Date de changement de statut')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gestion_formations.session', verbose_name='Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gestion_inscriptions.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('UNEXCUSED', 'Non excusé'), ('EXCUSED', 'Excusé'), ('LATE', 'En retard')], default='ABSENT', max_length=50, verbose_name='Statut de présence')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gestion_formations.seance', verbose_name='Séance')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gestion_inscriptions.enrollment', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('enrollment', 'seance')},
            },
        ),
    ]
