# Generated by Django 5.2 on 2025-04-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_inscriptions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom du type d'évaluation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Type d'évaluation",
                'verbose_name_plural': "Types d'évaluation",
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_evaluation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Poids de l'évaluation")),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note')),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date de l'évaluation")),
                ('commentaires', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='gestion_inscriptions.enrollment', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
    ]
