# Generated by Django 5.2 on 2025-04-19 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_formations', '0002_rename_lieu_seance_lieu_seance'),
        ('gestion_inscriptions', '0003_enrollment_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom du type d'évaluation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Type d'évaluation",
                'verbose_name_plural': "Types d'évaluation",
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_evaluation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Poids de l'évaluation")),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note')),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date de l'évaluation")),
                ('commentaires', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='gestion_inscriptions.enrollment', verbose_name='Inscription')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='gestion_formations.seance', verbose_name='Séance associée')),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='gestion_notes.evaluationtype', verbose_name="Type d'évaluation")),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
    ]
