# Generated by Django 5.2 on 2025-04-28 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_formations', '0001_initial'),
        ('gestion_notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='Formateur'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='seance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='gestion_formations.seance', verbose_name='Séance associée'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='gestion_notes.evaluationtype', verbose_name="Type d'évaluation"),
        ),
    ]
